name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger this workflow when a new version tag is pushed (e.g. v1.0.1)

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.x'
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Decode google-services.json
        run: |
          cat << 'EOF' > android/app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF

      - name: Build APK
        run: flutter build apk --release

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release ${{ github.ref_name }}"
          generateReleaseNotes: true
          allowUpdates: true
          removeArtifacts: true
          makeLatest: true
          draft: false
          prerelease: false
